{
 "title": "Vega - Markets",
 "tags": [ "vega" ],
 "time": { "from": "now-12h", "to": "now-30m" },
 "templating": {
  "list": [
   {
    "name": "Market",
    "label": "Market",
    "query": "select name from public.markets m "
   },
   { "name": "feesType", "label": "Fees type", "query": "Infrastructure,Maker,Liquidity" }
  ]
 },
 "panels": [
  {
   "title": "Maker fees",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \n    to_timestamp(\"f\".\"time\") AS time,\n    m.name  as tags,\n    SUM(sell_maker_fee) AS \"Sell fees\",\n    SUM(buy_maker_fee) AS \"Buy fees\"\n  FROM \"public\".\"fees15min\" as \"f\"\n  join public.markets as \"m\" on m.vega_id = f.vega_market_id\n  where m.name IN ($Market) AND \"f\".\"time\" IS NOT NULL\n  GROUP BY m.name, time\n  ORDER BY time\n  "
    }
   ]
  },
  {
   "title": "Infrastructure fees",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \n    to_timestamp(\"f\".\"time\") AS time,\n    m.name  as tags,\n    SUM(sell_infrastructure_fee) AS \"Sell fees\",\n    SUM(buy_infrastructure_fee) AS \"Buy fees\"\n  FROM \"public\".\"fees15min\" as \"f\"\n  join public.markets as \"m\" on m.vega_id = f.vega_market_id\n  where m.name IN ($Market) AND \"f\".\"time\" IS NOT NULL\n  GROUP BY m.name, time\n  ORDER BY time\n  "
    }
   ]
  },
  {
   "title": "Vega - Markets fees",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "constant": 6.5,
     "dataPath": "markets",
     "endTimePath": "endTime",
     "queryText": "query{\n  markets{\n    name\n    fees{\n      factors{\n        makerFee\n        infrastructureFee\n        liquidityFee\n      }\n    }\n  }\n}"
    }
   ]
  },
  {
   "title": "Liquidity fees",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT \n    to_timestamp(\"f\".\"time\") AS time,\n    m.name  as tags,\n    SUM(sell_liquidity_fee) AS \"Sell fees\",\n    SUM(buy_liquidity_fee) AS \"Buy fees\"\n  FROM \"public\".\"fees15min\" as \"f\"\n  join public.markets as \"m\" on m.vega_id = f.vega_market_id\n  where m.name IN ($Market) AND \"f\".\"time\" IS NOT NULL\n  GROUP BY m.name, time\n  ORDER BY time\n  "
    }
   ]
  },
  {
   "title": "Vega - Assets",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "constant": 6.5,
     "dataPath": "assets",
     "endTimePath": "endTime",
     "queryText": "query{\n  assets{\n    symbol\n    source{\n      __typename\n    }\n  }\n}"
    }
   ]
  }
 ]
}